//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDICollection.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyDICollection.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        internal static string Achievements {
            get {
                return ResourceManager.GetString("Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements: .
        /// </summary>
        internal static string Achievements2 {
            get {
                return ResourceManager.GetString("Achievements2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACHIEVEMENT UNLOCKED!.
        /// </summary>
        internal static string AchievemetsUnlock {
            get {
                return ResourceManager.GetString("AchievemetsUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New figure added to your collection!.
        /// </summary>
        internal static string AddFigure {
            get {
                return ResourceManager.GetString("AddFigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string ButtonCheckUpdates {
            get {
                return ResourceManager.GetString("ButtonCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Code on GitHub.
        /// </summary>
        internal static string ButtonViewCode {
            get {
                return ResourceManager.GetString("ButtonViewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect.
        /// </summary>
        internal static string Collect {
            get {
                return ResourceManager.GetString("Collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is free to use and made with love. If you find it useful and want to support the development or buy me a coffee, I would greatly appreciate it! ☕💙.
        /// </summary>
        internal static string ContributionsMessage {
            get {
                return ResourceManager.GetString("ContributionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figure removed from your collection..
        /// </summary>
        internal static string DeleteFigure {
            get {
                return ResourceManager.GetString("DeleteFigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figure.
        /// </summary>
        internal static string Figure {
            get {
                return ResourceManager.GetString("Figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanned figure was not found in your collection or the database..
        /// </summary>
        internal static string Figurenotfound {
            get {
                return ResourceManager.GetString("Figurenotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filters.
        /// </summary>
        internal static string FilterApplyButton {
            get {
                return ResourceManager.GetString("FilterApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filters.
        /// </summary>
        internal static string FilterClearButton {
            get {
                return ResourceManager.GetString("FilterClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔎 Filters.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall of Fame.
        /// </summary>
        internal static string HallOffFame {
            get {
                return ResourceManager.GetString("HallOffFame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string LanguagePopupTitle {
            get {
                return ResourceManager.GetString("LanguagePopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer: This application is an unofficial fan-made project. All images, names, and trademarks related to Disney Infinity are the property of Disney Enterprises, Inc. There is no official affiliation, sponsorship, or endorsement by Disney..
        /// </summary>
        internal static string LegalDisclaimerText {
            get {
                return ResourceManager.GetString("LegalDisclaimerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing with the Infinity Base....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the App.
        /// </summary>
        internal static string MenuAboutApp {
            get {
                return ResourceManager.GetString("MenuAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string MenuChangeLanguage {
            get {
                return ResourceManager.GetString("MenuChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributions.
        /// </summary>
        internal static string MenuContributions {
            get {
                return ResourceManager.GetString("MenuContributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        internal static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Number: .
        /// </summary>
        internal static string ModelNumber {
            get {
                return ResourceManager.GetString("ModelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Disc.
        /// </summary>
        internal static string MyDiscs {
            get {
                return ResourceManager.GetString("MyDiscs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Figures.
        /// </summary>
        internal static string MyFigures {
            get {
                return ResourceManager.GetString("MyFigures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC is disabled. Turn it on to scan your figures..
        /// </summary>
        internal static string NFCDisabled {
            get {
                return ResourceManager.GetString("NFCDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device does not support NFC scanning..
        /// </summary>
        internal static string NFCNotSupported {
            get {
                return ResourceManager.GetString("NFCNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap your figure or disc to the back of your phone to scan it....
        /// </summary>
        internal static string NFCScanMessage {
            get {
                return ResourceManager.GetString("NFCScanMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No achievements unlocked yet.
        /// </summary>
        internal static string NoAchievementsMessage {
            get {
                return ResourceManager.GetString("NoAchievementsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned.
        /// </summary>
        internal static string Owned {
            get {
                return ResourceManager.GetString("Owned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces:.
        /// </summary>
        internal static string PiecesLabel {
            get {
                return ResourceManager.GetString("PiecesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Disc.
        /// </summary>
        internal static string PowerDisc {
            get {
                return ResourceManager.GetString("PowerDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Disney Infinity Collection.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section under construction! Soon you&apos;ll be able to see all your collection&apos;s achievements and trophies here..
        /// </summary>
        internal static string UnderConstruction {
            get {
                return ResourceManager.GetString("UnderConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique:.
        /// </summary>
        internal static string UniqueLabel {
            get {
                return ResourceManager.GetString("UniqueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universe: .
        /// </summary>
        internal static string Universe {
            get {
                return ResourceManager.GetString("Universe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
